spring:
  data:
    mongodb:
      uri: mongodb+srv://thanhnghiat42_db_user:yqpvwPOczWuExr0J@coursedb.oind0z4.mongodb.net/?appName=courseDb
      database: courseDb
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: seanpaul1402@gmail.com
    password: "bsuu joea zjdl koqc"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/

mailboxlayer:
  api:
    key: 19dacce41e42ff30bc496ec3164e1cb0

jwt:
  secret: shapio-super-secret-key-abcxyz1234567890

app:
  upload-dir: uploads/

# ============================================
# PayOS Payment Configuration
# ============================================
payos:
  client-id: 20f87798-7fcc-4c38-9ad8-2db958f5e806
  api-key: 4ec884f6-d69d-44ce-b69b-0277ffcd28cc
  checksum-key: 945e5605eb1eb9be573fa0d1733aca3bbe9ebe834fa0993d52cc81455613a209

  # Endpoints
  api-base-url: https://api-merchant.payos.vn

  # URLs you registered on PayOS dashboard (adjust to your FE url / public webhook url)
  return-url: http://localhost:5174/payment/return
  cancel-url: http://localhost:5174/payment/cancel
  webhook-url: http://localhost:8080/api/payment/payos/webhook
